fof/urls.py
from django.urls import path
from fof.views import fof, about

app_name = 'fofapp'
urlpatterns = [
    path('experiments', fof, name="fof"),
    path('about', about, name="about"),
]

webfriends/urls.py
from . import regbackend
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

import fof
import image
import resulttable

urlpatterns = [
    path('', include('image.urls')),
    path('', include('resulttable.urls')),
    path('experiments/', views.table, name="experiments"),

    path('fof/', include('fof.urls', namespace='fofapp')),
    path('admin/', admin.site.urls),

    path('accounts/register/', regbackend.MyRegistrationView.as_view(),
         name='register_custom'),
    path('accounts/', include('registration.backends.default.urls')),

    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),
    path('', views.home, name="home"),

    path('register/complete/', TemplateView.as_view(template_name='registration/registration_complete.html'), name='registration_complete'),
    path('register/closed/',
         TemplateView.as_view(template_name='registration/registration_closed.html'),
         name='registration_disallowed'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

fof/models.py
from django.contrib.auth.models import User
from django.db import models
from webfriends.models import UsuarioFriends


class FoFAlgorithm(models.Model):
    idFoF = models.AutoField(primary_key=True)
    nameFoF = models.CharField(null=False, blank=False, max_length=100)
    descFoF = models.TextField(null=True, blank=False)
    commandFoF = models.TextField(null=False, blank=False)


    class Meta:
        managed = True
        db_table = 'fof_algorithm'

    def __str__(self):
        return self.nameFoF

fof/forms.py
from django import forms
from .models import FoFAlgorithm
from django.core.exceptions import ValidationError
from django.shortcuts import render

# maximum size 25MB input file
def file_size(value):
    limit = 26214400
    if value.size > limit:
        raise ValidationError(('Arquivo muito grande.'
                              'Tamanho máximo deve ser de 20MB.'))
        return render(request, "FoF.html")


class FoFForm(forms.Form):
    # Algorithm = forms.ChoiceField(
    #    label="Algorithm", required=True, queryset=FoFAlgorithm.objects.all(),
    #    choices=(("sequentialn2", "FoF O(n²) Sequencial"), ("paralleln2omp", "FoF O(n²) Paralelo OpenMP"), ("paralleln2acc", "FoF O(n²) Paralelo OpenACC")))
    Algorithm = forms.ModelChoiceField(label="Algorithm", required=True, queryset=FoFAlgorithm.objects.all(), empty_label= "---", initial=3)
    Input = forms.FileField(label="Input file", required=True, validators=[file_size])
    Rperc = forms.FloatField(label="Percolation radius", required=True)
    #Numproc = forms.IntegerField(label="Number of processes", required=False)

fof/views.py
from django.conf import settings
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect
from fof.forms import FoFForm
from fof.models import FoFAlgorithm
from fof.tasks import RunFoFSerial
from resulttable.models import Execution

@csrf_protect
def fof(request):
    if request.method == 'POST':
        form = FoFForm(request.POST, request.FILES or None)
        if not form.is_valid():
            title = "Experiments %s" % (request.user)
            context = {
                "form": form,
                'title': title
            }
            return render(request, "fof/FoF.html", context)

        idAlg = request.POST.get('Algorithm')
        processos = request.POST.get('processos')
        kernels = request.POST.get('kernels')
        rperc = request.POST['Rperc']

        usuario = User.objects.get(username=request.user)
        alg = FoFAlgorithm.objects.get(idFoF=idAlg)

        execution = Execution(
            request_by=usuario.usuariofriends,
            algorithm = alg.nameFoF,
        )
        execution.save()

        #pega o arquivo de entrada:
        if(request.FILES):
            fileIn = request.FILES["Input"]
            execution.inputFile = fileIn
            execution.save()

            queryInputFile = (
                settings.MEDIA_ROOT +
                execution.inputFile.name.replace('./', '/')
            ).replace(' ', '\ ')

            queryOutputFile = queryInputFile
            queryOutputFile = queryOutputFile.replace('input', 'output')

            print("Query input file:" + queryInputFile)
            print("Query output file:" + queryOutputFile)

            outputFilePath = settings.MEDIA_ROOT + 'users/user_' + str(execution.request_by.usuario.id) + '/' + str(execution.id) + '/'
            logFilePath = settings.MEDIA_ROOT + 'users/user_' + str(execution.request_by.usuario.id) + '/' + str(execution.id) + '/logfile'

        run = RunFoFSerial(alg.commandFoF, rperc, processos, kernels, execution.id, queryInputFile, outputFilePath, logFilePath)

        return HttpResponseRedirect(reverse('experiments'))

    form = FoFForm(request.POST or None)
    title = "Experiments %s" % (request.user)
    context = {
        "title": title,
        "form": form
    }

    return render(request, 'fof/FoF.html', context)

def about(request):
    query_results = FoFAlgorithm.objects.all()
    return render(request, 'fof/about.html', {"results" : query_results})

templates/fof/FoF.html
{%extends "base.html" %}


{% load staticfiles %}
{% load crispy_forms_tags %}
{% crispy form %}

{% block head_title%}Friends of Friends Algorithm{%endblock%}


{% block content %}

	{% if request.user.is_authenticated %}
		<div id='row-form' class="row">
			<div id="colForm" class="col-sm-3 col-md-3"></div>
		  <div id="colForm" class="col-sm-6 col-md-6">
				  <form id='form_exec' method='POST' action='{% url "fofapp:fof" %}' enctype="multipart/form-data">
				{% csrf_token %}

					  <div id="div_id_Algorithm" class="form-group"> <label for="id_Algorithm" class="col-form-label  requiredField">
                		Algorithm<span class="asteriskField">*</span> </label>
						  <div class="">
						  <select name="Algorithm" class="select form-control" id="id_Algorithm" onclick='test()'>
							  {% if Algorithm == None %}
                                    <option selected="selected" value="0"></option>
							  {% endif %}
							  <option value="1" >FoF O(n²) Sequential</option>
							  <option value="2">FoF O(n²) Parallel OpenMP</option>
							  <option value="3">FoF O(n²) Parallel OpenACC</option>
							  <option value="4">FoF O(nlogn) Sequential</option>
						  </select>
					  </div> </div>


						<div class="form-group" id="extra">
							<td><label for="idnumprocessos">Number of processes:</label></td>
							<td><input name="processos" type="text" maxlength="20" id="idnumprocessos" class="form-control" value="{{processos}}"></td>
						</div>

					   <div class="form-group" id="extra2">
							<td><label for="idnumkernels">Number of GPU kernels:</label></td>
							<td><input name="kernels" type="text" maxlength="20" id="idnumkernels" class="form-control" value="{{kernels}}"></td>
						</div>



					  <div id="div_id_Input" class="form-group"> <label for="id_Input" class="col-form-label  requiredField">
                Input file<span class="asteriskField">*</span> </label> <div class=""> <input type="file" name="Input" class="clearablefileinput" required="" id="id_Input"> </div> </div>

					  <div id="div_id_Rperc" class="form-group"> <label for="id_Rperc" class="col-form-label  requiredField">
                Percolation radius<span class="asteriskField">*</span> </label> <div class=""> <input type="number" name="Rperc" step="any" class="numberinput form-control" required="" id="id_Rperc"> </div> </div


					<!--{# <div id="formContent"> Necessario para nao bugar com erro de validacao do crispy #}-->
						<!--{{form|crispy}}    {# Crispy que falha nao retorna formulario com o csrf_token  #}-->
					<!--{# </div>				   Isso ocasionava um erro de acesso. (gambiarra no javascript) #}-->


					<input id='execute' class='btn btn-primary'  type="submit" value="Run">

				</form>
		  	</div>
		  	<div id="colForm" class="col-sm-3 col-md-3"></div>
		</div>

	{%else%}
		Login to proceed.
	{%endif%}
{%endblock%}

templates/fof/about.html
<!DOCTYPE html>
{%extends "base.html" %}
{% load static %}
{% block jumbotron %}
<div class="jumbotron">
  <h1><center>Friends-of-Friends</center></h1>

    <div style="width:80%;" class="container">
    <p>Friends-of-Friends (FoF) is an algorithm used to identify structures in galaxy distribution based on physical proximity
        [1]. It gets as input, data from N-body computer simulations in a 3-dimensional space [2]
        used to identify halos and to identify structures in numerical simulations too [3].</p>
    <p>
        FoF is one of the most popular grouping percolation methods, specially because the other methods, as the Bayesian, for example,
        are not publicly available and are more difficult to code. Besides, the FoF uses just a single free parameter defined by the
        user, that determines the threshold of the linking length called percolation radius</p>

     <p>
        The basic idea of the algorithm is: consider a sphere of radius R around each particle of a given set. If within that sphere
        exist other particles, they will be considered as belonging to the same halo and be called "friends". Then, we take a sphere
        around each friend and the procedure continues using the rule "any friend of my friend is my friend". The procedure stops when
        no new friend can be added to the group. The images below represents the FoF execution:</p>
        <p>
            <center>
            <img src="{% static '/img/fof1.png' %}" alt="Italian Trulli" align="middle" width="50%"/>
            <figcaption>Input particles position.</figcaption>
            <img src="{% static 'img/fof2.png' %}" alt="Italian Trulli" align="middle" width="50%"/>
            <figcaption>Considering a sphere of radius R around each particle.</figcaption>
            <img src="{% static 'img/fof3.png' %}" alt="Italian Trulli" align="middle" width="50%"/>
            <figcaption>Groups classified by their gravitational position.</figcaption>
            </center>
        </p>


    </div>

    <p><b>Available algorithms:</b></p>

		<div id="postlist">
			<div class="panel">

                {% for alg in results %}
                  <div class="panel-heading">
                        <div class="text-center">
                            <div class="row">
                                <div class="col-sm-9">
                                    <h4 class="pull-left">{{ alg.nameFoF }}</h4>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="panel-body">
                        <p>{{ alg.descFoF }}</p>
                        <a href="#"> Download {{ alg.commandFoF }}</a>
                    </div>
                {% endfor %}
        </div>
        </div>

  <h3><center>References</center></h3>
    <ol>
      <li>HUCHRA, J. P., GELLER, M. J. Groups of Galaxies I. Nearby groups. 1982. In: The astrophysical, v. 257, p. 423 - 437.</li>
      <li>DAVIS, M., Efstathiou, G., Frenk, C.S., White, S.D.M., 1985. The evolution of large scale structure in a universe dominated by cold dark matter. In: Astrophys. J. 292, 371–394. doi:10.1086/163168.</li>
      <li>KNEBE, A. et al.; Haloes gone MAD: The Halo‐Finder Comparison Project. 2011. In: Monthly Notices of the Royal Astronomical Society. vol. 415(3), p. 2293-2318</li>
      <li>DUARTE, M., Mamon, G. A. How well does the Friends-of-Friends algorithm recover group properties from galaxy catalogs limited in both distance and luminosity? 2014. In: Monthly Notices of the Royal Astronomical Society. 440(2). doi: 10.1093/mnras/stu378. </li>
    </ol>

</div>
{% endblock %}