fof/urls.py
from django.urls import path
from fof.views import fof, about

app_name = 'fofapp'
urlpatterns = [
    path('experiments', fof, name="fof"),
    path('about', about, name="about"),
]

image/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('experiments/image/wavelet',
         views.wavelet,
         name="wavelet"),
    ]

webfriends/urls.py
from . import regbackend
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

import fof
import image
import resulttable

urlpatterns = [
    path('', include('image.urls')),
    path('', include('resulttable.urls')),
    path('experiments/', views.table, name="experiments"),

    path('fof/', include('fof.urls', namespace='fofapp')),
    path('admin/', admin.site.urls),

    path('accounts/register/', regbackend.MyRegistrationView.as_view(),
         name='register_custom'),
    path('accounts/', include('registration.backends.default.urls')),

    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),
    path('', views.home, name="home"),

    path('register/complete/', TemplateView.as_view(template_name='registration/registration_complete.html'), name='registration_complete'),
    path('register/closed/',
         TemplateView.as_view(template_name='registration/registration_closed.html'),
         name='registration_disallowed'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

image/models.py
from django.db import models
from webfriends.models import UsuarioFriends

class ImageAlgorithm(models.Model):
    idAlg = models.AutoField(primary_key=True)
    nameAlg = models.CharField(null=False, blank=False, max_length=100)
    desc = models.CharField(null=True, blank=False, max_length=500)

    class Meta:
        managed = True
        db_table = 'image_algorithm'

    def __str__(self):
        return self.nameAlg

image/forms.py
from django import forms
from django.utils.safestring import mark_safe

# maximum size 25MB input file
def file_size(value):
    limit = 26214400
    if value.size > limit:
        raise ValidationError(('Arquivo muito grande. '
                              'Tamanho máximo deve ser de 20MB.'))
        return render(request, "image.html")


class WaveletForm(forms.Form):
    Input = forms.ImageField(label="Image", required=True, validators=[file_size])
    Wavelet = forms.ChoiceField(label=mark_safe("<a href='http://scikit-image.org/docs/dev/api/skimage.restoration.html#denoise-wavelet'>Wavelet</a>"), choices=(("db1", "db1"), ("db2", "db2"), ("db3", "db3")))
    Method = forms.ChoiceField(label=mark_safe("<a href='http://scikit-image.org/docs/dev/api/skimage.restoration.html#denoise-wavelet'>Method</a>"), choices=(("visushrink", "VisuShrink"), ("bayeshrink", "BayesShrink")))
    ShiftAmount = forms.IntegerField(label=mark_safe("<a href='http://scikit-image.org/docs/dev/auto_examples/filters/plot_cycle_spinning.html'>Shift amount</a>"), min_value=0, max_value=100)
    Format = forms.ChoiceField(label="Format", choices=(("bmp", "BMP"), ("png", "PNG")))

image/views.py
from django.conf import settings
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect
from image.forms import WaveletForm
from image.tasks import WaveletExperiment
from resulttable.models import Execution
from webfriends.views import home


@csrf_protect
def wavelet(request):

    if request.method == 'POST':

        form = WaveletForm(request.POST, request.FILES or None)

        if not form.is_valid():
            title = "Experiments %s" % (request.user)

            context = {
                "form": form,
                "title": title
            }

            return render(request, "wavelet.html", context)

        d_User = User.objects.get(username=request.user)
        wavelet = request.POST.get("Wavelet")
        method = request.POST.get("Method")
        samount = request.POST.get("ShiftAmount")

        if method == 'visushrink':
            method = 'VisuShrink'
        else:
            method = 'BayesShrink'

        execution = Execution(
            request_by=d_User.usuariofriends
        )

        execution.save()

        if request.FILES:
            fileIn = request.FILES["Input"]
            execution.inputFile = fileIn
            execution.save()
            queryInputFile = (
                settings.MEDIA_ROOT +
                execution.inputFile.name.replace('./', '/')
            ).replace(' ', '\ ')
            queryOutputFile = queryInputFile
            queryOutputFile = queryOutputFile.replace('input', 'output')

        # Run Experiment

        outputFilePath = settings.MEDIA_ROOT + 'users/user_' + \
            str(execution.request_by.usuario.id) + \
            '/' + str(execution.id) + '/output.' + request.POST.get("Format")

        logFilePath = settings.MEDIA_ROOT + 'users/user_' + \
            str(execution.request_by.usuario.id) + \
            '/' + str(execution.id) + ".log"

        print(outputFilePath)

        run = WaveletExperiment.delay((wavelet, method, samount), request.user.email, queryInputFile, outputFilePath, logFilePath, execution.id)

        return HttpResponseRedirect(reverse('experiments'))

    form = WaveletForm(request.POST or None)

    title = "Experiments %s" % (request.user)
    context = {
        "title": title,
        "form": form
    }

    return render(request, "wavelet.html", context)

templates/about.html
{%extends "base.html" %}


{% block jumbotron %}
<div class="jumbotron">
  <h2>About</h2>
  <p>This Virtual Observatory allows remote execution of some applications in Astronomy.</p>
  <p>The portal offer parallel versions of the <b>Friends-of-Friends</b> algorithm for astronomical objects classification, and algorithms for image restoration using <b>wavelet filtering.</b>
The users can perform as many executions as they wants, and at the end of each they can download the output file and a log file.</p>
  <p>This project was originally developed by Otávio Migliavacca Madalosso in 2015 as a conclusion work in his graduation in Computer Science at Federal University of Santa Maria (UFSM).
Currently, this is being continued by Ana Solórzano and Vinícius Monego.</p>
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title%}{%endblock%}</title>
    {% include 'head_css.html'%}

    <script>
      function test() {
          if (document.getElementById('id_Algorithm').value == '2') {
              document.getElementById('extra').style.display = 'block';
              document.getElementById('extra2').style.display = 'none';
          } else if (document.getElementById('id_Algorithm').value == '3'){
              document.getElementById('extra').style.display = 'block';
              document.getElementById('extra2').style.display = 'block';
          }else {
              document.getElementById('extra').style.display = 'none';
              document.getElementById('extra2').style.display = 'none';
          }
      }
     </script>


    </head>

  <body>
   {% load staticfiles %}
    {% include 'navbar.html' %}

      {% block messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable"
                 style="padding: 5px; width: 20%; float:right; text-align: center;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
    {% endblock messages %}

    <div style="margin-bottom:50px;padding-top:10px;" class="container">

        {% block jumbotron %}
        {% endblock %}

        {% block content %}
        {% endblock %}
    </div>


    <div class="container-fluid">
      <div class="row">
      {% block container %}
      {% endblock %}
      </div>
    </div>

    {% include "javascript.html" %}

  </body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}Contact{% endblock %}


{% block content %}
<div class="row">
  <div class="col-md-3 col-sm-3"></div>
  <div class="col-sm-6 col-md-6 center-block">
    <form method="POST" action=".">{% csrf_token %}
      {{form|crispy}}
      <p style="text-align: center" class="lead">
        <input class='btn btn-primary center-block' type="submit" value="Send"></p>
    </form>
  </div>
  <div class="col-md-3 col-sm-3"></div>
</div>

{% endblock %}

templates/experiments.html
{%extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% crispy form %}

{% block head_title%}FoF{%endblock%}

{% block content %}
{% if request.user.is_authenticated %}
<div id='row-form' class="row">
  <div id="colForm" class="col-sm-3 col-md-3"></div>
  <div id="colForm" class="col-sm-6 col-md-6">
    <form id='form_exec' method='POST' action='.' enctype="multipart/form-data">
      {% csrf_token %}
      {# <div id="formContent"> Necessario para nao bugar com erro de validacao do crispy #}
	{{form|crispy}}    {# Crispy que falha nao retorna formulario com o csrf_token  #}
	{# </div>				   Isso ocasionava um erro de acesso. (gambiarra no javascript) #}
      <input id='execute' class='btn btn-primary' type="submit" value="Executar">
    </form>
  </div>
  <div id="colForm" class="col-sm-3 col-md-3"></div>
</div>
{%else%}
Faça o login para prosseguir
{%endif%}
{%endblock%}

templates/footer.html
<footer class="footer">
<div class="container">
			<div class="row text-center text-xs-center text-sm-left text-md-left" style="padding-top:10px;padding-bottom:10px">
				<div class="col-xs-10 col-sm-4 col-md-4" >
					<h5>Menu</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="{% url 'home' %}">Home</a></li>
						<li><a href="{% url 'about' %}">About</a></li>
						<li><a href="{% url 'fofapp:about' %}">FoF</a></li>
						<li><a href="{% url 'wavelet' %}">Wavelet</a></li>
					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>Documentation</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="link">link</a></li>
						<li><a href="link">link</a></li>
						<li><a href="link">link</a></li>
					</ul>
				</div>
                <div class="col-xs-12 col-sm-4 col-md-4">
					<ul class="list-unstyled list-inline social text-center">
                        <h5>Contact us</h5><br/>
						<li class="list-inline-item"><a href="{% url 'contact' %}"><i class="fa fa-envelope"></i></a></li>
					</ul>
				</div>
			</div>
		</div>

  <div class="container">
    <p class="text-muted text-center">Otávio Madalosso, Ana Solórzano and Vinícius Monego</p>
    <p class="text-muted text-center">2015</p>
  </div>
</footer>

templates/forms.html
<form method="POST" action=".">{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Enviar">
</form>

templates/head_css.html
{% load staticfiles %}
{% block head_css %}
    <!-- Bootstrap core CSS -->
    <link href="https://unpkg.com/bootstrap@4.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/footer.css'%}" rel="stylesheet">
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head_title %}{{title}}{% endblock %}

<!--TABELA DOS EXPERIMENTOS -->
{% block content %}
<div class="row">
  {% if data != None %}
  <div class = "col-sm-12 col-md-12 text-center">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th><input id="checkHeader" type="checkbox" value=""></th>
          <th>ID</th>
          <th data-align="center">Requisition date</th>
          <th data-align="center">Status</th>
          <th>Algorithm</th>
          <th>Time</th>
          <th>Input file</th>
          <th>Output file</th>
          <th>Log file</th>
        </tr>
      </thead>

      <tbody id="tableExp">
        {% for exp in data %}
        <tr>
          <td><input type="checkbox" value="{{exp.id}}"></td>
          <td>{{exp.id}}</td>
          <td>{{exp.date_requisition}}</td>
          <td>
            {% if exp.status == 1 %}
            Waiting
            {% else %}
            {% if exp.status == 2 %}
            Running
            {% else %}
            {% if exp.status == 3 %}
            Finished
            {% endif %}
            {% endif %}
            {% endif %}
          </td>
          <td>{{exp.algorithm}}</td>
          <td>
            {% if exp.time == -1 %}
              -
            {% else %}
              {{exp.time|floatformat:-4}} s
            {% endif %}
          </td>
          <td>
            {% if exp.inputFile%}
            <a  href="{% url 'downloadInputFile'%}?id={{exp.id}}"><button type="button" class="btn btn-success">Download</button></a>
            {% else %}
            <button type="button" class="btn btn-warning disabled">No input</button>
            {% endif %}
          </td>
          <td>
            {% if exp.outputFile%}
            <a  href="{% url 'downloadOutputFile'%}?id={{exp.id}}"><button type="button" class="btn btn-success">Download</button></a>
            {% else %}
            <button type="button" class="btn btn-warning disabled">No results</button>
            {% endif %}
          </td>
          <td>
            {% if exp.logFile %}
              <a  href="{% url 'downloadLogFile'%}?id={{exp.id}}"><button type="button" class="btn btn-success">Download</button></a>
            {% else %}
              <button type="button" class="btn btn-warning disabled">No log</button>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  {% else %}
    <div id="colForm" class="col-sm-3 col-md-3"></div>
    <div id="colForm" class="col-sm-6 col-md-6 text-center">
      <hr>
      <p1>You have no experiments.</p1>
      <hr>
    </div>
    <div id="colForm" class="col-sm-3 col-md-3"></div>
  {% endif %}

</div>

      <div style="padding-bottom:10px" >
      <ul class="nav navbar-nav navbar-right">
        <ul class="pagination no-margin pull-right">

          {% if data.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ data.previous_page_number }}">Previous</a></li>
          {% endif %}

          {% for page, value in pagesIndex.items %}
            {% if value > 0 %}
              <li class="page-item"><a class="page-link" href="?page={{value}}">{{value}}</a></li>
            {% endif %}

              <!--{% if page == 2 %}-->
              <!--<li class='active'><a href="#">{{value}}</a></li>-->
              <!--{% else %}-->
              <!--<li><a href="?page={{value}}">{{value}}</a></li>-->
              <!--{% endif %}-->

          {% endfor %}

          {% if data.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ data.next_page_number }}">Next</a></li>
          {% endif %}

        </ul>
      </ul>
    </div>

    <form id="formRemove" method='POST' action='{% url 'expRemove' %}' enctype="multipart/form-data">
      {% csrf_token %}
      <input type="submit" id="btExcluir" class="btn btn-default btn-sm" value="Remove">
    </form>

{% endblock %}

templates/image.html
{%extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% crispy form %}

{% block head_title%}Remoção de Ruído em Imagens{%endblock%}

{% block content %}
	{% if request.user.is_authenticated %}
		<div id='row-form' class="row">
			<div id="colForm" class="col-sm-3 col-md-3"></div>
		  <div id="colForm" class="col-sm-6 col-md-6">
				  <form id='form_exec' method='POST' action='{% url "image" %}' enctype="multipart/form-data">
				{% csrf_token %}
					{# <div id="formContent"> Necessario para nao bugar com erro de validacao do crispy #}
						{{form|crispy}}    {# Crispy que falha nao retorna formulario com o csrf_token  #}
					{# </div>				   Isso ocasionava um erro de acesso. (gambiarra no javascript) #}
					<input id='execute' class='btn btn-primary' type="submit" value="Executar">
				</form>
		  	</div>
		  	<div id="colForm" class="col-sm-3 col-md-3"></div>
		</div>
	{%else%}
		Faça o login para prosseguir
	{%endif%}
{%endblock%}

templates/javascript.html
    {% load staticfiles %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://unpkg.com/jquery@3.3.1/dist/jquery.min.js"></script>
    <script src="https://unpkg.com/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/js-cookie@2.2.0/src/js.cookie.js"></script>
    <script src="https://unpkg.com/popper.js@1.14.3/dist/umd/popper.min.js"></script>
    <script src="{% static 'js/home.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/experiment.js' %}"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script> -->

templates/navbar.html
<!-- Static navbar -->
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'home' %}">Web portal</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="navbar-nav mr-auto">
	  <li class="nav-item">
	  <a class="nav-link" href="{% url 'about' %}">About</a>
	  {% if request.user.is_authenticated %}
	  <li class="nav-item">
	  <a class="nav-link" href="{% url 'experiments' %}">Experiments</a>
		<li class="nav-item">
		  <div class="dropdown">
			<button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Friends-of-Friends</button>
			  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				<a class="dropdown-item" href="{% url 'fofapp:fof' %}">Run</a>
				  <a class="dropdown-item" href="{% url 'fofapp:about' %}">About</a>
			  </div>
		 </div>

	<li class="nav-item">
	  <div class="dropdown">
	    <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Images</button>
	    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
	      <a class="dropdown-item" href="{% url 'wavelet' %}">Wavelet</a>
	    </div>
	  </div>
	  {% endif %}
      </ul>

      <ul class="navbar-nav ml-auto">
	{% if request.user.is_authenticated %}
	<li class="nav-item mr-sm-2">
	  <a>{{user}}</a>
	<li class="nav-item mr-sm-2">
	  <a href="{% url 'auth_logout' %}">Sair</a>
	{% else %}
	<li class="active mr-sm-2"><a href="{% url 'registration_register' %}">Sign up</a></li>
	{% endif %}
      </ul>

      {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
      <form class="form-inline" method="POST" action="{% url 'auth_login' %}">{%csrf_token%}
	<div class="form-group">
	  <input type="text" class="form-control mr-sm-2" name="username" placeholder="Username">
	</div>
	<div class="form-group">
	  <input type="password" class="form-control mr-sm-2" name="password" placeholder="Password">
	</div>
	<button type="submit" class="btn btn-default">Sign in</button>
      </form>
      {%endif%}
    </div><!--/.nav-collapse -->
  </div>
</nav>

templates/wavelet.html
{%extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% crispy form %}

{% block head_title%}Remoção de Ruído em Imagens via Transformada Wavelet{%endblock%}

{% block content %}
{% if request.user.is_authenticated %}
<div id='row-form' class="row">
  <div id="colForm" class="col-sm-3 col-md-3"></div>
  <div id="colForm" class="col-sm-6 col-md-6">
    <form id='form_exec' method='POST' action='{% url "wavelet" %}' enctype="multipart/form-data">
      {% csrf_token %}
      {# <div id="formContent"> Necessario para nao bugar com erro de validacao do crispy #}
	{{form|crispy}}    {# Crispy que falha nao retorna formulario com o csrf_token  #}
	{# </div>				   Isso ocasionava um erro de acesso. (gambiarra no javascript) #}
      <input id='execute' class='btn btn-primary' type="submit" value="Run">
    </form>
  </div>
  <div id="colForm" class="col-sm-3 col-md-3"></div>
</div>
{%else%}
Faça o login para prosseguir
{%endif%}
{%endblock%}

templates/welcome.html
{%extends "base.html" %}

{% load crispy_forms_tags %}

{% block head_title%}{{title}}{% endblock %}

{% block jumbotron%}
      <div class="jumbotron">
        <h1>Web Portal for Execution of Applications in Astronomy</h1>
        <p> Web portal for remote execution of experiments with algorithms to process data from simulations in the Astronomy field.</p>

          {% if request.user.is_authenticated == false %}
          <a class="btn btn-lg btn-primary" href="{% url 'register_custom' %}" role="button">Registre-se &raquo;</a>
          {% endif %}
        </p>
      </div>
{% endblock %}

{% block container %}
{% include "footer.html" %}
{% endblock %}